name = "VLBIPlots"
uuid = "0260e397-8112-41bf-b55a-6b4577718f00"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.20"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AccessorsExtra = "33016aad-b69d-45be-9359-82a41f556fd4"
AxisKeysExtra = "b7a0d2b7-1990-46dc-b5dd-87820ecd1b09"
DataManipulation = "38052440-ad76-4236-8414-61389b2c5143"
InterferometricModels = "b395d269-c2ec-4df6-b679-36919ad600ca"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MakieExtra = "54e234d5-9986-40d8-815f-a5e42de435f6"
RectiGrids = "8ac6971d-971d-971d-971d-971d5ab1a71a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Accessors = "0.1.32"
AccessorsExtra = "0.1.72"
AxisKeysExtra = "0.1.11"
DataManipulation = "0.1.16"
InterferometricModels = "0.1.19"
IntervalSets = "0.5.3, 0.6, 0.7"
InverseFunctions = "0.1.14"
LinearAlgebra = "1"
MakieExtra = "0.1.15"
RectiGrids = "0.1.18"
StaticArrays = "1.9.3"
Statistics = "1"
Unitful = "1.10.1"
julia = "1.9"
