name = "VLBIPlots"
uuid = "0260e397-8112-41bf-b55a-6b4577718f00"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.10"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
DataPipes = "02685ad9-2d12-40c3-9f73-c6aeda6a7ff5"
InterferometricModels = "b395d269-c2ec-4df6-b679-36919ad600ca"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MakieExtra = "54e234d5-9986-40d8-815f-a5e42de435f6"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Accessors = "0.1.32"
DataPipes = "0.2.7, 0.3"
InterferometricModels = "0.1.1"
IntervalSets = "0.5.3, 0.6, 0.7"
MakieExtra = "0.1.1"
Unitful = "1.10.1"
julia = "1.9"
